app/blueprints/cart.py
import re
from config import get_cursor
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from ..controllers.user_controllers import login_required, get_session_info
# from ..controllers.product_controller import get_or_create_cart
# from ..controllers.cart_controller import update_cart_item_quantities,get_cart_items_by_cartid, get_product_detai_by_cart_item_id, get_cart_items_image
from decimal import Decimal


cart = Blueprint(
    'cart',
    __name__,
    static_folder='static',
    template_folder='templates'
)

@cart.route('/')
@login_required
def display_cart():
     # get user_id and role_id from session
    is_login, user_id, role_id,discount_rate = get_session_info()
    # check if user has a cart
    dbconn = get_cursor()
    dbconn.execute("SELECT id FROM carts WHERE user_id=%s", (user_id,))
    cart = dbconn.fetchone()
    # if user does not have a cart, flash a message to the user that the cart is empty  
    if not cart:
        return render_template('cart/shopping_cart_page.html')
    # if user has a cart, get the items in the cart
    else:
        dbconn.execute("SELECT * FROM cart_items WHERE cart_id=%s", (cart[0],))
        cart_items = dbconn.fetchall()
        # if cart_items is empty, flash a message to the user that the cart is empty
        if not cart_items:
            return render_template('cart/shopping_cart_page.html')
        # if cart_items is not empty, get the details of the items in the cart
        else:
            cart_items_list = []
            cart_total = 0
            for cart_item in cart_items:
                # create a dictionary to store the details of the cart item
                cart_item_details = {}
                # get the details of the cart item from the cart_items table
                cart_item_details['cart_item_id'] = cart_item[0]
                cart_item_details['product_id'] = cart_item[2]
                cart_item_details['variant_id'] = cart_item[3]
                cart_item_details['order_quantity'] = cart_item[4]
                cart_item_details['order_price'] = cart_item[5]
                # get more details of the cart item from the product_variants, products, product_colors, sizes, and product_images tables
                select_query="""
                SELECT
                    p.product_name,
                    p.is_active,
                    pc.color_name,
                    s.size_name,
                    pv.stock_quantity,
                    p.base_price,
                    pv.color_id
                FROM product_variants pv
                    JOIN products p ON pv.product_id = p.id
                    JOIN product_colors pc ON pv.color_id = pc.id
                    JOIN sizes s ON pv.size_id = s.id
                WHERE pv.id = %s;
                """
                dbconn.execute(select_query, (cart_item[3],))
                product_detail = dbconn.fetchone()
                if not product_detail:
                    flash('Product not found', 'error')
                    # return render_template('cart/shopping_cart_page.html')
                else:
                    total_price_for_item = cart_item[4] * cart_item[5]  # order_quantity * current_price
                    cart_total += total_price_for_item
                    cart_total =Decimal(cart_total)
                    percent_to_earn = Decimal("0.10")  
                    order_points = cart_total * percent_to_earn

                    # add the product details to the cart_item_details dictionary
                    cart_item_details['product_name'] = product_detail[0]
                    cart_item_details['is_active'] = product_detail[1]
                    cart_item_details['color_name'] = product_detail[2]
                    cart_item_details['size_name'] = product_detail[3]
                    cart_item_details['stock_quantity'] = product_detail[4]
                    cart_item_details['current_price'] = product_detail[5]
                    cart_item_details['price_changed'] = cart_item[5] != product_detail[5]
                    cart_item_details['out_of_stock'] = cart_item[4] > product_detail[4]

                    # get product image urls
                    select_query="""
                    SELECT
                        pi.image_url
                    FROM product_images pi
                    WHERE pi.product_id = %s AND pi.color_id = %s;
                    """
                    dbconn.execute(select_query, (cart_item[2],product_detail[6]))
                    product_images = dbconn.fetchall()

                    # add the product image urls to the cart_item_details dictionary
                    cart_item_details['image_urls'] = [product_image[0] for product_image in product_images]
                    #calculate the total price of the cart
                   
                # add the cart_item_details to the cart_items_list
                cart_items_list.append(cart_item_details)
            
            return render_template('cart/shopping_cart_page.html',cart_items_list=cart_items_list, cart_total=cart_total,order_points=order_points)

@cart.route('/update_cart_item', methods=['POST'])
@login_required
def update_cart_item():
    #get updated quantity and cart_item_id from the form
    cart_updates = {}
    for key in request.form:
        if key.startswith('quantity_'):
            cart_item_id = key.split('_')[1]   
            quantity = request.form[key]            
            try:
                quantity = int(quantity)
                cart_updates[cart_item_id] = quantity
            except ValueError:                
                print(f"Invalid quantity for cart item {cart_item_id}")
    update_cart_item_quantities(cart_updates)
    flash("Cart updated successfully!", "success")
    return redirect(url_for('cart.display_cart'))

def update_cart_item_quantities(cart_updates):
    dbconn = get_cursor()  
    try:
        for cart_item_id, quantity in cart_updates.items():
            if quantity > 0:
                update_query = "UPDATE cart_items SET quantity=%s WHERE id=%s"
                dbconn.execute(update_query, (quantity, cart_item_id))
            else:
                print(f"Invalid quantity {quantity} for cart item {cart_item_id}")
    except Exception as e:
        print("An error occurred:", e)
        dbconn.rollback() 
        
@cart.route('/delete_cart_item/<int:cart_item_id>', methods=['GET'])
@login_required
def delete_cart_item(cart_item_id):
    dbconn = get_cursor()
    dbconn.execute("DELETE FROM cart_items WHERE id=%s", (cart_item_id,))
    return redirect(url_for('cart.display_cart'))

templates/cart/shopping_cart_page.html
{% extends 'components/base.html' %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<section class="customer-shopping-cart">

    <div class="shopping-cart-container">
        <div class="shopping-cart-header">
            {% if cart_items_list %}
            <P class="text-uppercase cart-title">YOUR CART</P>

            <p class="point-notification">
                <i class="fa-regular fa-star"></i>Complete your order and earn <span class="order-points">{{
                    order_points|default(0, true)|round }}</span>
                Possum Points for a discount on a future purchase
            </p>
        </div>

        <div class="shopping-cart-content">
            <div class="table-responsive">
                <form method="POST" action="{{ url_for('cart.update_cart_item') }}">
                    <table class="table align-middle">
                        <thead>
                            <tr class="text-uppercase">
                                <th class="item-name-img-group" scope="col">product</th>
                                <th class="item-other-group" scope="col">price</th>
                                <th class="item-other-group" scope="col">quantity</th>
                                <th class="item-other-group" scope="col">subtotal</th>
                                <th class="item-action-group" scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items_list %}
                            <tr id="item-row-{{ loop.index0 }}">
                                <td>
                                    <div class="item-name-img">
                                        <div class="cart-img-container">
                                            <img src="{{ 'https://raw.githubusercontent.com/LUMasterOfAppliedComputing2024S1/COMP639S1_Project_2_Group_AK_IMGS/main/'+ cart_item.image_urls[0] }}"
                                                alt="product image">
                                                <!-- <img src="{{ url_for('static', filename='images/each_category/' + cart_item.image_urls[0]) }}"
                                                alt="product image"> -->
                                        </div>
                                        <div class="cart-item-name">
                                            <p>{{ cart_item.product_name }}</p>
                                            <p class="cart-item-size">Size: {{cart_item.size_name}}</p>
                                            <p class="cart-item-color">Standard Colours: {{cart_item.color_name}}</p>

                                        </div>

                                    </div>
                                </td>
                                <td>
                                    <p class="current-price">$ {{ cart_item.order_price }} NZD</p>
                                </td>
                                <td>
                                    <div class="cart-input-group">
                                        <div class="input-group-prepend">
                                            <button type="button"
                                                onclick="changeQuantity(false, '{{ loop.index0 }}')">-</button>
                                        </div>
                                        {% if session.logged_in == True and session.role_id == 1 %}
                                        <input type="number" aria-invalid="false" class="form-control quantity-input"
                                            id="quantity-{{ loop.index0 }}" name="quantity_{{ cart_item.cart_item_id }}"
                                            value="{{ cart_item.order_quantity }}" min="1"
                                            max="{{cart_item.stock_quantity}}"
                                            oninput="updateSubtotal('{{ loop.index0 }}')"
                                            data-price="{{ cart_item.order_price }}">
                                        {% elif session.logged_in == True and session.role_id == 2 %}
                                        <input type="number" aria-invalid="false" class="form-control quantity-input"
                                            id="quantity-{{ loop.index0 }}" name="quantity_{{ cart_item.cart_item_id }}"
                                            value="{{ cart_item.order_quantity }}" min="10"
                                            max="{{cart_item.stock_quantity}}"
                                            oninput="updateSubtotal('{{ loop.index0 }}')"
                                            data-price="{{ cart_item.order_price }}">
                                        {% endif %}
                                        <div class="input-group-append">
                                            <button type="button"
                                                onclick="changeQuantity(true, '{{ loop.index0 }}')">+</button>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="cart-subtotal-price">$ <span id="subtotal-{{ loop.index0 }}">{{
                                            cart_item.order_price * cart_item.order_quantity }}</span> NZD</p>
                                </td>
                                <td>
                                    <a href="#" data-bs-toggle="modal"
                                        data-bs-target="#deleteConfirmModal{{ cart_item.cart_item_id }}">
                                        <svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1"
                                            xmlns="http://www.w3.org/2000/svg"
                                            xmlns:xlink="http://www.w3.org/1999/xlink"
                                            title="Remove Long Sleeves Boat Neck Midi Dress"
                                            aria-label="Remove Long Sleeves Boat Neck Midi Dress"
                                            aria-describedby="icon-title-Trash" aria-labelledby="icon-title-Trash"
                                            titleid="icon-title-Trash">
                                            <title></title>
                                            <g id="Icon/Trash/24px" stroke="none" stroke-width="1" fill="none"
                                                fill-rule="evenodd">
                                                <path
                                                    d="M20.7769877,4.84298476 L20.7769877,6.26403271 L19.7603662,6.26403271 L19.7603662,18.5712635 C19.7603662,20.4645127 18.22599,22 16.3316297,22 L16.3316297,22 L7.76089952,22 C5.86765033,22 4.33327408,20.4645127 4.33327408,18.5712635 L4.33327408,18.5712635 L4.33327408,6.26403271 L3,6.26403271 L3,4.84298476 L20.7769877,4.84298476 Z M18.3393183,6.26514377 L5.75543309,6.26514377 L5.75543309,18.5712635 C5.75543309,19.6767699 6.65428203,20.577841 7.76089952,20.577841 L7.76089952,20.577841 L16.3316297,20.577841 C17.4382472,20.577841 18.3393183,19.6767699 18.3393183,18.5712635 L18.3393183,18.5712635 L18.3393183,6.26514377 Z M10.377561,8.57637438 L10.377561,17.5559753 L8.95651304,17.5559753 L8.95651304,8.57637438 L10.377561,8.57637438 Z M14.8218079,8.57637438 L14.8218079,17.5559753 L13.40076,17.5559753 L13.40076,8.57637438 L14.8218079,8.57637438 Z M15.2217901,2 L15.2217901,3.42104795 L8.55541976,3.42104795 L8.55541976,2 L15.2217901,2 Z"
                                                    id="Combined-Shape" fill="#253746"></path>
                                            </g>
                                        </svg>
                                    </a>
                                    <div class="modal fade" id="deleteConfirmModal{{ cart_item.cart_item_id }}"
                                        tabindex="-1"
                                        aria-labelledby="deleteConfirmModalLabel{{ cart_item.cart_item_id }}"
                                        aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title"
                                                        id="deleteConfirmModalLabel{{ cart_item.cart_item_id }}">Confirm
                                                        Delete</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to delete this item?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Cancel</button>
                                                    <a href="{{url_for('cart.delete_cart_item', cart_item_id= cart_item.cart_item_id)}}"
                                                        class="btn btn-danger">Confirm Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr style="text-align:right">
                                <td colspan="5">
                                    <div class="cart-item-total">
                                        <p class="cart-item-total-title">Cart Total:</p>
                                        <p class="cart-item-total-price">$ <span
                                                id="cart-total-price">{{cart_total}}</span> NZD</p>
                                    </div>
                                </td>
                            </tr>

                        </tbody>
                    </table>
                    <div class="cart-item-submit-button">
                        <a href="{{ url_for('checkout.display_checkout_page') }}" class="btn mt-5">Checkout</a>
                        <button class="btn mt-5" type="submit">Update Cart</button>

                    </div>
                </form>
            </div>
        </div>
        {% else %}
        <div class="shopping-cart-content">
            <div class="empty-cart">
                <p>Your cart is empty</p>
                <a href="{{ url_for('home') }}" class="btn">Continue Shopping</a>
            </div>
        </div>
        {% endif %}

</section>
{% endblock %}