app/blueprints/client_pay_invoice.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from config import get_cursor
from ..controllers.user_controllers import get_session_info
from ..models.order_model import get_order_info, get_order_sum
import json
from decimal import Decimal
import math

# SCRUM-82 a Corporate Client pay invoices by Danfeng
client_pay_invoice = Blueprint(
    'client_pay_invoice',
    __name__,
    static_folder='static',
    template_folder='templates'
)

# This function converts Decimal objects to strings for JSON serialization.
def serialize_invoice_list(invoice_list):
    serialized_list = []
    for invoice in invoice_list:
        serialized_invoice = [str(item) if isinstance(item, Decimal) else item for item in invoice]
        serialized_list.append(serialized_invoice)
    return json.dumps(serialized_list)

# the client displays all unpaid invoices 
@client_pay_invoice.route('/', methods=['GET'] )
def display_invoice():
    is_login, user_id, role_id, discount_rate = get_session_info()
    if role_id != 2:
        return redirect(url_for('users.login'))
    else:
        page = request.args.get('page', 1, type=int)
        per_page = 10
        
        invoice_list = []
        cursor = get_cursor()
        try:
            sql_count = """
                SELECT COUNT(*) 
                FROM invoices 
                WHERE user_id=%s AND is_paid=0
            """
            cursor.execute(sql_count, (user_id,))
            total_invoices = cursor.fetchone()[0]

            total_pages = math.ceil(total_invoices / per_page)
            offset = (page - 1) * per_page

            sql = """
                SELECT id, order_id, total_incl_gst, shipping_fee, total_amount
                FROM invoices 
                WHERE user_id=%s AND is_paid=0
                LIMIT %s OFFSET %s
            """
            cursor.execute(sql, (user_id, per_page, offset))
            invoice_list = cursor.fetchall()
            serialized_invoice_list = serialize_invoice_list(invoice_list)
        except Exception as e:
            print(f"An error occurred: {e}")
            flash('An error occurred. Please try again later.', 'danger')
        
        return render_template(
            '/client_pay_invoice/client_view_invoice.html',
            serialized_invoice_list=serialized_invoice_list,
            invoice_list=invoice_list,
            page=page,
            total_pages=total_pages
        )

# the client chooses to pay all unpaid invoices    
@client_pay_invoice.route('/display_payment_page_all', methods=['POST'])
def display_payment_page_all():
    is_login, user_id, role_id, discount_rate = get_session_info()
    total = 0
    if role_id != 2:
        return redirect(url_for('users.login'))
    else:
        invoice_list_json = request.form.get('invoice_list')
        if invoice_list_json:
            try:
                invoice_list = json.loads(invoice_list_json)
                total = sum(Decimal(invoice[4]) for invoice in invoice_list if len(invoice) > 4)
                serialized_invoice_list = serialize_invoice_list(invoice_list)
            except Exception as e:
                print(f"An error occurred: {e}")  
                flash('An error occurred. Please try again later.', 'danger') 
                        
        return render_template('client_pay_invoice/client_payment_page_all.html', invoice_list = invoice_list, total = total, serialized_invoice_list = serialized_invoice_list )

# update the database after the client pays all unpaid invoices    
@client_pay_invoice.route('/confirm_payment_all', methods=['POST'])
def confirm_payment_all():
    is_login, user_id, role_id, discount_rate = get_session_info()
    if role_id != 2:
        return redirect(url_for('users.login'))
    else:
        invoice_list_json = request.form.get('invoice_list')
        if invoice_list_json:
            try:
                invoice_list = json.loads(invoice_list_json)                
                cursor = get_cursor()
                for invoice in invoice_list:
                    cursor.execute("UPDATE invoices SET is_paid = %s WHERE id = %s", (1, invoice[0]))
                    cursor.execute('INSERT INTO payments (user_id, invoice_id, payment_date, payment_type_id) VALUES (%s, %s, NOW(), %s)', (user_id, invoice[0], 1))
                    cursor.execute("SELECT total_amount FROM invoices WHERE id = %s", (invoice[0],))
                    total_amount = cursor.fetchone()[0]
                    cursor.execute("UPDATE corporate_clients SET available_credit = available_credit+ %s WHERE user_id = %s", (total_amount, user_id))
                flash(f'Payment has been made', 'success')
            except Exception as e:
                    print(f"An error occurred: {e}")
                    flash('An error occurred. Please try again later.', 'danger')      
        return redirect(url_for('client_pay_invoice.display_invoice'))
    

# the client view the detail of an order
@client_pay_invoice.route('/view_order/<int:order_id>', methods=['GET'])  
def view_order(order_id):
    is_login, user_id, role_id, discount_rate = get_session_info()
    order_detail = []
    order_sum = []
    if role_id != 2:
        return redirect(url_for('users.login'))
    else:
        order_detail = get_order_info(order_id) 
        order_sum = get_order_sum(order_id) 
        return render_template('/client_pay_invoice/client_view_order.html',order_id = order_id, order_detail = order_detail, order_sum = order_sum)

# the client chooses to pay a specific unpaid invoice 
@client_pay_invoice.route('/display_payment_page/<int:invoice_id>')
def display_payment_page(invoice_id):
    is_login, user_id, role_id, discount_rate = get_session_info()
    invoice = []
    if role_id != 2:
        return redirect(url_for('users.login'))
    else:
        try:
            cursor = get_cursor()
            cursor.execute("SELECT id, order_id, total_amount FROM invoices WHERE id = %s", (invoice_id,))
            invoice = cursor.fetchone()
        except Exception as e:
            print(f"An error occurred: {e}")  
            flash('An error occurred. Please try again later.', 'danger') 

        return render_template('client_pay_invoice/client_payment_page.html', invoice = invoice)

# update the database after the client pays a specific unpaid invoice
@client_pay_invoice.route('/confirm_payment/<int:invoice_id>', methods=['POST'])
def confirm_payment(invoice_id):
    is_login, user_id, role_id, discount_rate = get_session_info()
    if role_id != 2:
        return redirect(url_for('users.login'))
    else:
        try:
            cursor = get_cursor()
            cursor.execute("UPDATE invoices SET is_paid = %s WHERE id = %s", (1, invoice_id))
            cursor.execute('INSERT INTO payments (user_id, invoice_id, payment_date, payment_type_id) VALUES (%s, %s, NOW(), %s)', (user_id, invoice_id, 1))
            cursor.execute("SELECT total_amount FROM invoices WHERE id = %s", (invoice_id,))
            total_amount = cursor.fetchone()[0]
            cursor.execute("UPDATE corporate_clients SET available_credit = available_credit+ %s WHERE user_id = %s", (total_amount, user_id))
            flash(f'Payment of invoice {invoice_id} has been made', 'success')
        except Exception as e:
                print(f"An error occurred: {e}")
                flash('An error occurred. Please try again later.', 'danger')      

        return redirect(url_for('client_pay_invoice.display_invoice'))

templates/client_pay_invoice/client_payment_page.html
{% extends 'components/base.html' %}
{% block title %}Checkout{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<section class="checkout">
    <form action="{{ url_for('client_pay_invoice.confirm_payment', invoice_id = invoice[0] ) }}" method="POST">
        <div class="checkout-content">
            <div class="checkout-content-left">
                <div class="payment-method">
                    <div class="container mt-1">

                        <div id="creditCardSection" class="card">
                            <div class="card-header">
                                <p>Credit/debit card</p>
                                <!-- Card logos -->
                                <div>
                                    <img alt="VISA"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/0169695890db3db16bfe.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                    <img alt="MAESTRO"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/37fc65d0d7ac30da3b0c.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                    <img alt="MASTERCARD"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/ae9ceec48b1dc489596c.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                    <img alt="AMEX"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/f11b90c2972f3811f2d5.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="cardNumber">Card Number</label>
                                    <input type="text" class="form-control" id="cardNumber" placeholder="Card Number"
                                        required pattern="\d{13,16}"
                                        title="Card number must be between 13 and 16 digits.">
                                </div>

                                <div class="form-group">
                                    <label for="cardName">Name on Card</label>
                                    <input type="text" class="form-control" id="cardName" placeholder="Name on Card"
                                        required pattern="[A-Za-z\s]{1,10}"
                                        title="Name must be letters only and up to 10 characters long.">
                                </div>
                                <div class="form-row">
                                    <div>
                                        <label for="cardMonth">Month</label>
                                        <input type="text" class="form-control" id="cardMonth" placeholder="MM" required
                                            pattern="(0[1-9]|1[0-2])" title="Month must be MM format (01-12).">
                                    </div>
                                    <div>
                                        <label for="cardYear">Year</label>
                                        <input type="text" class="form-control" id="cardYear" placeholder="YY" required
                                            pattern="\d{2}" title="Year must be YY format.">
                                    </div>
                                    <div>
                                        <label for="cardCVC">CVC</label>
                                        <input type="text" class="form-control" id="cardCVC" placeholder="CVC" required
                                            pattern="\d{3}" title="CVC must be 3 digits.">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="checkout-content-right">
                <div class="review-order">
                    <p>Review Invoice:</p>
                    <div class="review-order-items">
                        <table class="table align-middle">
                            <thead>
                                <tr class="text-uppercase review-header">
                                    <th class="check-invoice-group" scope="col">Invoice ID</th>
                                    <th class="check-order-quantity" scope="col">Order ID</th>
                                    <th class="check-order-subtotal" scope="col">Outstanding Balance</th>
                                </tr>
                            </thead>
                            <tbody class="review-content">
                                <tr>
                                    <td class="order-quantity">
                                        <p>{{ invoice[0] }}</p>
                                    </td>
                                    <td class="order-quantity">
                                        <p>{{ invoice[1] }}</p>
                                    </td>
                                    <td>
                                        <p class="order-subtotal">$ <span id="subtotal">{{ invoice[2] }}</span> NZD</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <div class="cart_total_calculate">
                            
                            <div class="total-group dark">
                                <p>Total</p>
                                <p>NZD $<span id="total-incl-gst-shipping">{{ invoice[2] }}</span></p>
                            </div>

            
                        </div>
                    </div>
                </div>

                <div class="checkout-button">
                    <button type="submit" class="btn btn-dark text-uppercase mt-4">Confirm Payment</button>
                </div>
            </div>



        </div>
    </form>
</section>
{% endblock %}

templates/client_pay_invoice/client_payment_page_all.html
{% extends 'components/base.html' %}
{% block title %}Checkout{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<section class="checkout">
    <form action="{{ url_for('client_pay_invoice.confirm_payment_all' ) }}" method="POST">
        <div class="checkout-content">
            <div class="checkout-content-left">
                <div class="payment-method">
                    <div class="container mt-1">
                        <div id="creditCardSection" class="card">
                            <div class="card-header">
                                <p>Credit/debit card</p>
                                <!-- Card logos -->
                                <div>
                                    <img alt="VISA"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/0169695890db3db16bfe.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                    <img alt="MAESTRO"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/37fc65d0d7ac30da3b0c.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                    <img alt="MASTERCARD"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/ae9ceec48b1dc489596c.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                    <img alt="AMEX"
                                        src="https://cdn.shopify.com/shopifycloud/checkout-web/assets/f11b90c2972f3811f2d5.svg"
                                        role="img" width="38" height="24"
                                        class="_1fragemv9 _1fragemv4 _1fragemvi _1fragemql _1tgdqw66">
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="cardNumber">Card Number</label>
                                    <input type="text" class="form-control" id="cardNumber" placeholder="Card Number"
                                        required pattern="\d{13,16}"
                                        title="Card number must be between 13 and 16 digits.">
                                </div>
                                <div class="form-group">
                                    <label for="cardName">Name on Card</label>
                                    <input type="text" class="form-control" id="cardName" placeholder="Name on Card"
                                        required pattern="[A-Za-z\s]{1,10}"
                                        title="Name must be letters only and up to 10 characters long.">
                                </div>
                                <div class="form-row">
                                    <div>
                                        <label for="cardMonth">Month</label>
                                        <input type="text" class="form-control" id="cardMonth" placeholder="MM" required
                                            pattern="(0[1-9]|1[0-2])" title="Month must be MM format (01-12).">
                                    </div>
                                    <div>
                                        <label for="cardYear">Year</label>
                                        <input type="text" class="form-control" id="cardYear" placeholder="YY" required
                                            pattern="\d{2}" title="Year must be YY format.">
                                    </div>
                                    <div>
                                        <label for="cardCVC">CVC</label>
                                        <input type="text" class="form-control" id="cardCVC" placeholder="CVC" required
                                            pattern="\d{3}" title="CVC must be 3 digits.">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="checkout-content-right">
                <div class="review-order">
                    <p>Review Invoice:</p>
                    <div class="review-order-items">
                        <table class="table align-middle">
                            <thead>
                                <tr class="text-uppercase review-header">
                                    <th class="check-invoice-group" scope="col">Invoice ID</th>
                                    <th class="check-order-quantity" scope="col">Order ID</th>
                                    <th class="check-order-subtotal" scope="col">Outstanding Balance</th>
                                </tr>
                            </thead>
                            <tbody class="review-content">
                                {% for invoice in invoice_list %}
                                <tr>
                                    <td class="order-quantity">
                                        <p>{{ invoice[0] }}</p>
                                    </td>
                                    <td class="order-quantity">
                                        <p>{{ invoice[1] }}</p>
                                    </td>
                                    <td>
                                        <p class="order-subtotal">$ <span id="subtotal">{{ invoice[4] }}</span> NZD</p>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="cart_total_calculate">
                            
                            <div class="total-group dark">
                                <p>Total</p>
                                <p>NZD $<span id="total-incl-gst-shipping">{{ total }}</span></p>
                            </div>           
                        </div>
                    </div>
                </div>
                <div class="checkout-button">
                    <input type="hidden" id="invoice_list" name="invoice_list" value="{{ serialized_invoice_list }}">
                    <button type="submit" class="btn btn-dark text-uppercase mt-4">Confirm Payment</button>
                </div>
            </div>
        </div>
    </form>
</section>
{% endblock %}

templates/client_pay_invoice/client_view_invoice.html
{% extends 'components/base.html' %}
{% block title %}client view invoice{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<div class="client-view-invoice">
  <div class="client-view-invoice-container">

  
  <h2 class="text-center mb-4">Unpaid Invoice List</h2>
  <div class="d-flex justify-content-center mb-4">
    <form action="{{ url_for('client_pay_invoice.display_payment_page_all' ) }}" method="POST">
      <input type="hidden" id="invoice_list" name="invoice_list" value="{{ serialized_invoice_list }}">
      <button type="submit" class="btn btn-custom" style="min-width: 120px; font-size: 20px;">Pay All Invoices</button>
    </form>
  </div>
  <div class="table-responsive">
    <table class="table align-middle">
      <thead class="table-success">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Invoice ID</th>
          <th scope="col">Order ID</th>
          <th scope="col">Total Price (incl. GST)</th>
          <th scope="col">Shipping Fee (NZD)</th>
          <th scope="col">Discounted Price (NZD)</th>  
          <th scope="col">Pay Invoice</th>         
        </tr>
      </thead>
      <tbody>
        {% for invoice in invoice_list %}
        <tr>
          <th scope="row">{{ loop.index }}</th>
          <td>{{ invoice[0] | default('', true) }}</td>
          <td>
            <a href="{{url_for('client_pay_invoice.view_order', order_id = invoice[1] )}}"  class="btn btn-outline-success"><i class="bi bi-eye-fill"></i>{{ invoice[1] | default('', true) }}</a>
          </td>
          <td>{{ invoice[2] | default('', true)}}</td>
          <td>{% if invoice[3]==0 %} 0 {% else %} {{ invoice[3]| default('', true)}} {% endif %}</td>
          <td>{{ invoice[4] | default('', true)}}</td>   
          <td>
            <a href="{{url_for('client_pay_invoice.display_payment_page', invoice_id = invoice[0] )}}"  class="btn btn-outline-success"><i class="bi bi-eye-fill"></i>Pay This Invoice</a>
          </td>   
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="d-flex justify-content-between mt-4">
    <a href="{{ url_for('home') }}" class="btn btn-secondary" style="min-width: 120px; font-size: 17px;">Back</a>
    <nav aria-label="Page navigation" class="d-flex justify-content-end">
      <ul class="pagination">
          <li class="page-item {% if page <= 1 %}disabled{% endif %}">
              <a class="page-link" href="{{ url_for('client_pay_invoice.display_invoice', page=page-1) }}">Previous</a>
          </li>
          {% for p in range(1, total_pages + 1) %}
          <li class="page-item {% if p == page %}active{% endif %}">
              <a class="page-link" href="{{ url_for('client_pay_invoice.display_invoice', page=p) }}">{{ p }}</a>
          </li>
          {% endfor %}
          <li class="page-item {% if page >= total_pages %}disabled{% endif %}">
              <a class="page-link" href="{{ url_for('client_pay_invoice.display_invoice', page=page+1) }}">Next</a>
          </li>
      </ul>
  </nav>
  </div>
</div>
  
</div>
{% endblock %}

templates/client_pay_invoice/client_view_order.html
{% extends 'components/base.html' %}
{% block title %}Client View Order{% endblock %}
{% block content %}

<div class="container my-4 py-3" style="background-color: white; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <h1 class="text-center mb-4">Details of Order {{order_id}}</h1>
  
  <div class="table-responsive">
    <table class="table align-middle">
      <thead class="table-success">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Product ID</th>
          <th scope="col">Product Name</th>
          <th scope="col">Image</th>
          <th scope="col">Color</th>
          <th scope="col">Size</th>
          <th scope="col">Price (NZD)</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Price (NZD)</th>
        </tr>
      </thead>
      <tbody>
        {% for product in order_detail %}
        <tr>
          <th scope="row">{{ loop.index }}</th>
          <td>{{ product[0]| default('', true) }}</td>
          <td>{{ product[1]| default('', true) }}</td>
          <td>
            <img src="{{'https://raw.githubusercontent.com/LUMasterOfAppliedComputing2024S1/COMP639S1_Project_2_Group_AK_IMGS/main/' + (product[2] if product[2] else 'default_image.jpg')}}" alt="Product Photo" class="img-fluid" style="width: 60px; height: 80px;">
          </td>
          <td>{{ product[3] | default('', true)}}</td>
          <td>{{ product[4] | default('', true)}}</td>
          <td>{{ product[5] | default('', true)}}</td>
          <td>{{ product[6] | default('', true)}}</td>
          <td>{{ product[7] | default('', true)}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <h5 class="text-left mb-4"><strong>Total price including GST</strong> is: {{order_sum[0]}}NZD.      <strong>Shipping fee</strong> is: {{order_sum[1]}}NZD.      Total amount paid is: {{order_sum[2]}}NZD</h5>
  <h5 class="text-left mb-4"><strong>Delivery address</strong> is: {{order_sum[3]}}, {{order_sum[4]}}, {{order_sum[5]}}, {{order_sum[6]}}.      Post Code is: {{order_sum[7]}}</h5>
  <h5 class="text-left mb-4"><strong>Note</strong>: {{order_sum[8]}}</h5>
  <div class="d-flex justify-content-between mt-4">
    <a href="{{ url_for('client_pay_invoice.display_invoice') }}" class="btn btn-secondary" style="min-width: 120px;font-size: 17px;">Back</a>
  </div>
</div>
{% endblock %}