app/blueprints/manage_staff.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from config import get_cursor
from ..controllers.user_controllers import get_session_info, check_user_exists_by_email, check_user_exists_by_username, check_password
from werkzeug.security import generate_password_hash
import re
import datetime
import math

# SCRUM-29 Manager manage staff by Danfeng
manage_staff = Blueprint(
    'manage_staff',
    __name__,
    static_folder='static',
    template_folder='templates'
)

# manager or administrator display all staff
@manage_staff.route('/')
def display_all_staff():
    is_login, user_id, role_id, discount_rate = get_session_info()
    if is_login and (session.get('is_manager') == 1 or session.get('is_admin') == 1):
        page = request.args.get('page', 1, type=int)
        per_page = 10
        
        staff_list = []
        cursor = get_cursor()
        try:
            # Get the total number of staff
            sql_count = """
                SELECT COUNT(*)
                FROM users u
                JOIN employees e On u.id = e.user_id
                WHERE role_id = 3 AND is_manager = 0 AND is_admin = 0
            """
            cursor.execute(sql_count)
            total_staff = cursor.fetchone()[0]

            total_pages = math.ceil(total_staff / per_page)
            offset = (page - 1) * per_page

            # Get the paginated staff
            query = """
                SELECT u.id, username, email, first_name, last_name, phone, country, is_active
                FROM users u
                JOIN employees e On u.id = e.user_id
                WHERE role_id = 3 AND is_manager = 0 AND is_admin = 0  
                ORDER BY first_name, last_name
                LIMIT %s OFFSET %s
            """
            cursor.execute(query, (per_page, offset))
            staff_list = cursor.fetchall()
        except Exception as e:
            flash(f'An error occurred: {e}', 'error')
        
        return render_template(
            '/manage_staff/display_all_staff.html',
            staff_list=staff_list,
            page=page,
            total_pages=total_pages
        )
    else:
        flash('Please log in first', 'info')
        return redirect(url_for('users.login'))

# manager or administrator view and edit a specific staff
@manage_staff.route('/edit_staff/<int:staff_id>', methods=['GET','POST'])
def edit_staff(staff_id):
    is_login, user_id, role_id, discount_rate = get_session_info()
    if is_login ==True and (session.get('is_manager')==1 or session.get('is_admin')==1):
        if request.method == 'POST':
            email = request.form.get('email', '')
            first_name = request.form.get('first_name', '')
            last_name = request.form.get('last_name', '')
            phone = request.form.get('phone', '')
            street_address = request.form.get('street_address', '')
            city = request.form.get('city', '')
            state = request.form.get('state', '')
            country = request.form.get('country', '')
            post_code = request.form.get('post_code', '')
            is_active =request.form.get('is_active')
            
            if email and not re.match(r'[^@]+@[^@]+\.[^@]+', email):
                flash('Invalid email address!','error')
                return redirect(url_for('manage_staff.edit_staff', staff_id = staff_id))
            try:    
                cursor = get_cursor() 
                update_staff_query = "UPDATE users SET email = %s, first_name = %s, last_name = %s, phone = %s, street_address = %s, city = %s, state = %s, country = %s, post_code = %s, is_active = %s WHERE id = %s"
                cursor.execute(update_staff_query, (email, first_name, last_name, phone, street_address, city, state, country, post_code, is_active, staff_id ))
                flash('Update the staff successfully', 'success')
            except Exception as e:
                flash(f'An error occurred: {e}', 'error')

        query = """
            SELECT id, username, email, first_name, last_name, phone, street_address, city, state, country, post_code, is_active
            FROM users 
            WHERE id = %s """       
        staff_detail = []
        try:
            cursor = get_cursor()
            cursor.execute(query, (staff_id,))
            staff_detail = cursor.fetchone()  
        except Exception as e:
            flash(f'An error occurred: {e}', 'error')
  
        return render_template('/manage_staff/edit_staff.html', staff_detail = staff_detail)  
    else:
        flash('Please log in first', 'info')
        return redirect(url_for('users.login')) 

# manager or administrator add a new staff
@manage_staff.route('/add_staff', methods=['GET','POST'])
def add_staff():
    is_login, user_id, role_id, discount_rate = get_session_info()
    if is_login ==True and (session.get('is_manager')==1 or session.get('is_admin')==1):
        if request.method == 'POST':
            username= request.form.get('username')
            is_active =request.form.get('is_active') 
            email = request.form.get('email')
            password=request.form.get('password')
            confirm_password= request.form.get('confirm_password')
            first_name = request.form.get('first_name')
            last_name = request.form.get('last_name')

            phone = request.form.get('phone', '')
            street_address = request.form.get('street_address', '')
            city = request.form.get('city', '')
            state = request.form.get('state', '')
            country = request.form.get('country', '')
            post_code = request.form.get('post_code', '')
            
            # check if all fields are filled
            if not (username and first_name and last_name and email and password and confirm_password):
                flash('Please fill all fields.', 'error')
                return render_template('/manage_staff/add_staff.html')

            # check if the username is already registered
            if check_user_exists_by_username(username):
                flash('Username already registered, you can sign in directly.', 'error')
                return render_template('/manage_staff/add_staff.html')

            # check if the email is already registered
            if check_user_exists_by_email(email):
                flash('Email already registered, you can sign in directly.', 'error')
                return render_template('/manage_staff/add_staff.html')

            # check if the passwords match
            if password != confirm_password:
                flash('Passwords do not match.', 'error')
                return render_template('/manage_staff/add_staff.html')

            # check if the password is strong
            if not check_password(password):
                flash('Password is not strong.', 'error')
                return render_template('/manage_staff/add_staff.html')

            # hash the password
            hashed_password = generate_password_hash(password, method='pbkdf2:sha256', salt_length=8)
                  
            cursor = get_cursor()
            try:  
                cursor.execute(
                    "INSERT INTO users (username, email, hashed_password, first_name, last_name, phone, street_address, city, state, country, post_code, is_active, role_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                    (username, email, hashed_password, first_name, last_name, phone, street_address, city, state, country, post_code, is_active, 3)
                )
                user_id = cursor.lastrowid
                hire_date = datetime.date.today()
                cursor.execute(
                    "INSERT INTO employees (user_id, hire_date, job_title, is_admin, is_manager ) VALUES (%s, %s, %s, %s, %s)", (user_id, hire_date, 'staff', 0, 0)
                )  
                flash(
                    'Congratulations, your have added a staff account successfully.🎉🎉🎉', 'success')
            except Exception as e:
                flash(f'An error occurred: {e}', 'error')  

        return render_template('/manage_staff/add_staff.html')
    
    else:
        flash('Please log in first', 'info')
        return redirect(url_for('users.login')) 

templates/manage_staff/add_staff.html
{% extends 'components/base.html' %}
{% block title %}Add New Staff{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow">
                <div class="card-header text-white"  style="background-color: #b674b1;">
                    <h4>Add Staff Details</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ url_for('manage_staff.add_staff') }}">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="username" class="form-label"><strong>Username</strong><span style="color: red"> * </span>
                                </label>
                                <input type="text" class="form-control" id="username" name="username" value="" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="is_active" class="form-label"><strong>Status</strong><span style="color: red"> * </span></label>
                                <select class="form-select" id="is_active" name="is_active">
                                    <option value="1" selected>Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="email" class="form-label"><strong>Email:</strong><span style="color: red"> * </span></label>
                                <input type="email" class="form-control" id="email" name="email" value="" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="phone" class="form-label"><strong>Phone</strong></label>
                                <input type="text" class="form-control" id="phone" name="phone"  value=""  maxlength="20" >
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="password" class="form-label"><strong>Password</strong><span style="color: red"> * </span></label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="confirm_password" class="form-label"><strong>Confirm
                                        Password</strong><span style="color: red"> * </span></label>
                                <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="first_name" class="form-label"><strong>First Name</strong><span style="color: red"> * </span></label>
                                <input type="text" class="form-control" id="first_name" name="first_name"
                                    value="" maxlength="50" pattern="[A-Za-z]+" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="last_name" class="form-label"><strong>Last Name</strong><span style="color: red"> * </span></label>
                                <input type="text" class="form-control" id="last_name" name="last_name"
                                    value="" maxlength="50" pattern="[A-Za-z]+" required>
                            </div>
                          
                            <div class="col-md-12 mb-3">
                                <label for="street_address" class="form-label"><strong>Address</strong></label>
                                <input type="text" class="form-control" id="street_address" name="street_address" value="">
                            </div>    
                            <div class="col-md-6 mb-3">
                                <label for="city" class="form-label"><strong>City</strong></label>
                                <input type="text" class="form-control" id="city" name="city" value="">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="state" class="form-label"><strong>State</strong></label>
                                <input type="text" class="form-control" id="state" name="state" value="">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="country" class="form-label"><strong>Country</strong></label>
                                <input type="text" class="form-control" id="country" name="country" value="">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="post_code" class="form-label"><strong>Post Code</strong></label>
                                <input type="text" class="form-control" id="post_code" name="post_code"  value="">
                            </div>
                           
                        </div>
                        <div class="mb-4 d-flex justify-content-between">
                            <a href="{{ url_for('manage_staff.display_all_staff') }}"
                                class="btn btn-secondary my-3 "><strong>← Back to List</strong></a>
                            <button type="submit" class="btn btn-custom my-3"><strong>Creat New Staff</strong>
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

templates/manage_staff/display_all_staff.html
{% extends 'components/base.html' %}
{% block title %}Manage Staff{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<div class="container my-4 py-3" style="background-color: white; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <h2 class="text-center mb-4">Staff List</h2>
  <div class="d-flex justify-content-center mb-4">
    <a href="{{ url_for('manage_staff.add_staff') }}" class="btn btn-custom">Create Staff</a>
  </div>
  <div class="table-responsive">
    <table class="table align-middle table-striped">
      <thead class="table-success">
        <tr>
          <th scope="col">#</th>    
          <th scope="col">Username</th>
          <th scope="col">Email</th>
          <th scope="col">Name</th>          
          <th scope="col">Phone</th>
          <th scope="col">Country</th>
          <th scope="col">Status</th>
          <th scope="col">View and Edit</th>
        </tr>
      </thead>
      <tbody>
        {% for staff in staff_list %}
        <tr>
          <th scope="row">{{ loop.index }}</th>
          <td>{{ staff[1]| default('', true) }}</td>
          <td>{{ staff[2]| default('', true) }}</td>
          <td>{{ staff[3] | default('', true)}} {{ staff[4] | default('', true)}}</td>
          <td>{{ staff[5] | default('', true)}}</td>
          <td>{{ staff[6] | default('', true)}}</td>
          <td><span class="badge {{'bg-success' if staff[7] == 1 else 'bg-secondary'}}">{{ 'Active' if staff[7] == 1 else 'Inactive' }}</span></td>
          <td>
            <a href="{{ url_for('manage_staff.edit_staff', staff_id=staff[0]) }}" class="btn btn-outline-success"> View and Edit</a>       
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-between mt-4">
    <a href="{{ url_for('home') }}" class="btn btn-secondary" style="min-width: 120px;font-size: 17px;">Back</a>
    <nav aria-label="Page navigation" class="d-flex justify-content-end">
      <ul class="pagination">
          <li class="page-item {% if page <= 1 %}disabled{% endif %}">
              <a class="page-link" href="{{ url_for('manage_staff.display_all_staff', page=page-1) }}">Previous</a>
          </li>
          {% for p in range(1, total_pages + 1) %}
          <li class="page-item {% if p == page %}active{% endif %}">
              <a class="page-link" href="{{ url_for('manage_staff.display_all_staff', page=p) }}">{{ p }}</a>
          </li>
          {% endfor %}
          <li class="page-item {% if page >= total_pages %}disabled{% endif %}">
              <a class="page-link" href="{{ url_for('manage_staff.display_all_staff', page=page+1) }}">Next</a>
          </li>
      </ul>
  </nav>
  </div>
</div>
{% endblock %}

templates/manage_staff/edit_staff.html
{% extends 'components/base.html' %}
{% block title %}Edit Staff Details{% endblock %}
{% block content %}
{% include 'components/message.html' %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow">
                <div class="card-header bg-success text-white" >
                    <h4>Edit Staff Details</h4>
                </div>
                <div class="card-body my-3" >
                    <form method="POST" action="{{ url_for('manage_staff.edit_staff', staff_id=staff_detail[0]) }}">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="username" class="form-label"><strong>Username</strong></label>
                                <input type="text" class="form-control" id="username" value="{{ staff_detail[1] }}" disabled>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="is_active" class="form-label"><strong>Status</strong></label>
                                <select class="form-select" id="is_active" name="is_active">
                                    <option value="1" {% if staff_detail[11] == 1 %}selected{% endif %}>Active</option>
                                    <option value="0" {% if staff_detail[11] != 1 %}selected{% endif %}>Inactive</option>
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="first_name" class="form-label"><strong>First Name</strong></label>
                                <input type="text" class="form-control" id="first_name" name="first_name"
                                    value="{{ staff_detail[3] |default('', true) }}" maxlength="50" pattern="[A-Za-z]+">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="last_name" class="form-label"><strong>Last Name</strong></label>
                                <input type="text" class="form-control" id="last_name" name="last_name"
                                    value="{{ staff_detail[4] |default('', true) }}" maxlength="50" pattern="[A-Za-z]+">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="email" class="form-label"><strong>Email:</strong></label>
                                <input type="email" class="form-control" id="email" name="email"
                                    value="{{ staff_detail[2] |default('', true)}}">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="phone" class="form-label"><strong>Phone</strong></label>
                                <input type="text" class="form-control" id="phone" name="phone"
                                    value="{{ staff_detail[5] |default('', true) }}"  maxlength="20" >
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="street_address" class="form-label"><strong>Address</strong></label>
                                    <input type="text" class="form-control" id="street_address" name="street_address"
                                        value="{{ staff_detail[6] |default('', true) }}">
                            </div>    
                            <div class="col-md-6 mb-3">
                                <label for="city" class="form-label"><strong>City</strong></label>
                                <input type="text" class="form-control" id="city" name="city"
                                    value="{{ staff_detail[7] |default('', true) }}">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="state" class="form-label"><strong>State</strong></label>
                                <input type="text" class="form-control" id="state" name="state"
                                    value="{{ staff_detail[8] |default('', true) }}">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="country" class="form-label"><strong>Country</strong></label>
                                <input type="text" class="form-control" id="country" name="country"
                                    value="{{ staff_detail[9] |default('', true) }}">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="post_code" class="form-label"><strong>Post Code</strong></label>
                                <input type="text" class="form-control" id="post_code" name="post_code"
                                    value="{{ staff_detail[10] |default('', true) }}">
                            </div>
                            
                        </div>

                        <div class="mb-4 d-flex justify-content-between">
                            <a href="{{ url_for('manage_staff.display_all_staff') }}"
                                class="btn btn-secondary my-3 "><strong>← Back to List</strong></a>
                            <button type="submit" class="btn btn-success my-3"><strong>Update Details</strong>
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}