app/blueprints/customer_track_order.py
from flask import Blueprint, render_template, redirect, url_for, flash,request
from config import get_cursor
from ..controllers.user_controllers import get_session_info, login_required
from ..models.order_model import get_orders, get_order_info, get_order_sum
import math

# SCRUM-8 customer track order and payment by Danfeng
customer_track_order = Blueprint(
    'customer_track_order',
    __name__,
    static_folder='static',
    template_folder='templates'
)

# create a route to display the user's orders
@customer_track_order.route('/', methods=['GET'])
def list_order():
    is_login, user_id, role_id, discount_rate = get_session_info()
    if is_login and (role_id == 1 or role_id == 2):
        page = request.args.get('page', 1, type=int)
        per_page = 8
        
        all_orders = get_orders(user_id)
        total_orders = len(all_orders)
        
        # Pagination calculations
        total_pages = math.ceil(total_orders / per_page)
        offset = (page - 1) * per_page
        
        paginated_orders = all_orders[offset:offset + per_page]

        return render_template(
            '/customer_track_order/list_all_orders.html',
            all_orders=paginated_orders,
            page=page,
            total_pages=total_pages
        )
    else:
        flash('Please log in first', 'info')
        return redirect(url_for('users.login'))

    
# the customer view the detail of an order
@customer_track_order.route('/view_order/<int:order_id>', methods=['GET'])
@login_required    
def view_order(order_id):
    is_login, user_id, role_id,discount_rate = get_session_info()
    order_detail = []
    order_sum = []
    if is_login ==True and (role_id==1 or role_id==2):
        order_detail = get_order_info(order_id) 
        order_sum = get_order_sum(order_id) 
        return render_template('/customer_track_order/customer_view_order.html',order_id = order_id, order_detail = order_detail, order_sum = order_sum)
    else:
        flash('Please log in first', 'info')
        return redirect(url_for('users.login'))

    
# the user view receipt   
@customer_track_order.route('/view_receipt/<int:current_order_id>', methods=['GET'])
def view_receipt(current_order_id):
    is_login, user_id, role_id,discount_rate = get_session_info()
    if is_login ==True and (role_id==1 or role_id==2):
        try:
            cursor = get_cursor()
            cursor.execute("SELECT total_incl_gst, shipping_fee, total_amount, payment_date, type_name FROM invoices JOIN payments ON invoices.id=payments.invoice_id JOIN payment_types ON payments.payment_type_id=payment_types.id WHERE order_id=%s",(current_order_id,))
            receipt = cursor.fetchone()                
        except Exception as e:
            print(f"An error occurred: {e}")  
            flash('An error occurred. Please try again later.', 'danger')
        return render_template('/customer_track_order/view_receipt.html', receipt=receipt)
    else:  
        flash('Please log in first', 'info')
        return redirect(url_for('users.login'))

  

templates/customer_track_order/customer_view_order.html
{% extends 'components/base.html' %}
{% block title %}Staff View Order{% endblock %}
{% block content %}

<div class="customer-view-order-detail" >
  <div class="customer-view-order-detail-container">

  

  <h1 class="text-center mb-4">Details of Order {{order_id}}</h1>
  
  <div class="table-responsive">
    <table class="table align-middle">
      <thead class="table-success">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Product ID</th>
          <th scope="col">Product Name</th>
          <th scope="col">Image</th>
          <th scope="col">Color</th>
          <th scope="col">Size</th>
          <th scope="col">Price (NZD)</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Price (NZD)</th>
        </tr>
      </thead>
      <tbody>
        {% for product in order_detail %}
        <tr>
          <th scope="row">{{ loop.index }}</th>
          <td>{{ product[0]| default('', true) }}</td>
          <td>{{ product[1]| default('', true) }}</td>
          <td>
            <img src="{{'https://raw.githubusercontent.com/LUMasterOfAppliedComputing2024S1/COMP639S1_Project_2_Group_AK_IMGS/main/' + (product[2] if product[2] else 'default_image.jpg')}}" alt="Product Photo" class="img-fluid" style="width: 60px; height: 80px;">
          </td>
          <td>{{ product[3] | default('', true)}}</td>
          <td>{{ product[4] | default('', true)}}</td>
          <td>{{ product[5] | default('', true)}}</td>
          <td>{{ product[6] | default('', true)}}</td>
          <td>{{ product[7] | default('', true)}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <h5 class="text-left mb-4"><strong>Total price including GST</strong> is: {{order_sum[0]}} NZD.      <strong>Shipping fee</strong> is: {{order_sum[1]}} NZD.      Total amount paid is: {{order_sum[2]}} NZD</h5>
  <h5 class="text-left mb-4"><strong>Delivery address</strong> is: {{order_sum[3]}}, {{order_sum[4]}}, {{order_sum[5]}}, {{order_sum[6]}}.      Post Code is: {{order_sum[7]}}</h5>
  <h5 class="text-left mb-4"><strong>Note</strong>: {{order_sum[8]}}</h5>
  <div class="d-flex justify-content-between mt-4">
    <a href="{{ url_for('customer_track_order.list_order') }}" class="btn btn-secondary" style="min-width: 120px;font-size: 17px;">Back</a>
  </div>
</div>
</div>
{% endblock %}

templates/customer_track_order/list_all_orders.html
{% extends 'components/base.html' %}
{% block title %}List all Orders of a Customer{% endblock %}
{% block content %}

<div class="list-all-orders" >
  <div class="list-all-orders-contaniner">

  
  <h1 class="text-center mb-4">Order List</h1>
  
  <div class="table-responsive">
    <table class="table align-middle">
      <thead class="table-success">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Order ID</th>
          <th scope="col">Order Date</th>
          <th scope="col">Status</th>
          <th scope="col">Recipient Name</th>
          <th scope="col">Recipient Mobile</th>
          <th scope="col">Delivery Address</th>
          <th scope="col">View Details</th>
          <th scope="col">View Receipt</th>
        </tr>
      </thead>
      <tbody>
        {% for order in all_orders %}          
            <tr>
              <th scope="row">{{ loop.index }}</th>
              <td>{{ order[0]| default('', true) }}</td>
              <td>{{ order[2] | default('', true)}}</td>
              <td>
                {% if order[6] == 1 %}{{'Pending'}}{% endif %}
                {% if order[6] == 2 %}{{'Processing'}}{% endif %}
                {% if order[6] == 3 %}{{'Shipped'}}{% endif %}
                {% if order[6] == 4 %}{{'Delivered'}}{% endif %}               
              </td>
              <td>{{ order[7] | default('', true)}}</td>
              <td>{{ order[8] | default('', true)}}</td>          
              <td>{{ order[9] | default('', true)}}{{', '}}{{ order[10] | default('', true)}}</td>
              <td>
                <a href="{{url_for('customer_track_order.view_order', order_id = order[0] )}}"  class="btn btn-custom"><i class="bi bi-eye-fill"></i>Details</a>
              </td>  
              <td>
                <a href="{{url_for('customer_track_order.view_receipt', current_order_id = order[0])}}" class="btn btn-custom">Receipt</a>
              </td>
            </tr>          
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-between mt-4">
    <a href="{{ url_for('home') }}" class="btn btn-secondary" style="min-width: 120px;font-size: 17px;">Back</a>
    <nav aria-label="Page navigation" class="d-flex justify-content-end">
      <ul class="pagination">
          <li class="page-item {% if page <= 1 %}disabled{% endif %}">
              <a class="page-link" href="{{ url_for('customer_track_order.list_order', page=page-1) }}">Previous</a>
          </li>
          {% for p in range(1, total_pages + 1) %}
          <li class="page-item {% if p == page %}active{% endif %}">
              <a class="page-link" href="{{ url_for('customer_track_order.list_order', page=p) }}">{{ p }}</a>
          </li>
          {% endfor %}
          <li class="page-item {% if page >= total_pages %}disabled{% endif %}">
              <a class="page-link" href="{{ url_for('customer_track_order.list_order', page=page+1) }}">Next</a>
          </li>
      </ul>
  </nav>
  </div>
</div>
</div>
{% endblock %}

templates/customer_track_order/view_receipt.html
{% extends 'components/base.html' %}
{% block title %}View Receipt{% endblock %}
{% block content %}


<div class="min-vh-100 d-flex justify-content-center" style="background: linear-gradient(135deg, #af69b7 0%, #d294ce 100%);padding-top:3%; margin-top:0">

  <div style="width: 100%; max-width: 60vw;">
    <div class="container my-4 py-3" style="background-color: white; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
      <h3 class="text-center mb-4">Your Receipt</h3>
      <div class="card mb-5">
        <div class="card-body">
          <p class="card-text" style="font-size: 17px;"><strong>Total Price including GST:</strong> {{ receipt[0] }} NZD</p>
          <p class="card-text" style="font-size: 17px;"><strong>Shipping Fee:</strong> {{ receipt[1] }} NZD</p>
          <p class="card-text" style="font-size: 17px;"><strong>Total Cost:</strong> {{ receipt[2] }} NZD</p>
          <p class="card-text" style="font-size: 17px;"><strong>Payment Date:</strong> {{ receipt[3] }}</p>
          <p class="card-text" style="font-size: 17px;"><strong>Payment Type:</strong> {{ receipt[4] }}</p>
          
          <div class="d-flex justify-content-between mt-4">
            <a href="{{ url_for('customer_track_order.list_order') }}" class="btn btn-secondary" style="min-width: 120px;font-size: 17px;">Back</a>
          </div>
        </div>
      </div>      

    </div>
  </div>
</div>

{% endblock %}